#!/usr/bin/env python3
"""Generate docs/DEPS.md from real resolver data — never from memory.

Evidence-based dependency bookkeeping, required by AGENTS.md rule 6.

Usage (from repo root, in WSL or anywhere cargo works):
    python3 scripts/gen-deps.py            # writes docs/DEPS.md
    python3 scripts/gen-deps.py --check    # exit 1 if docs/DEPS.md is stale
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "DEPS.md"

# Tools used for verification only. They must never be linked or bundled.
# (licence, role) — role is always "oracle" here; see AGENTS.md "Oracles".
ORACLES = [
    ("poppler-utils `pdftotext`", "4.00 (Windows) / distro (WSL)", "GPL-2.0-or-later",
     "text-extraction oracle", "https://poppler.freedesktop.org/"),
    ("`qpdf`", "distro", "Apache-2.0", "structure validation (`--check`)",
     "https://qpdf.readthedocs.io/"),
    ("`mutool` (MuPDF)", "distro", "AGPL-3.0", "render/extract cross-check — CI only",
     "https://mupdf.com/licensing.html"),
    ("`ghostscript`", "distro", "AGPL-3.0", "cross-renderer fidelity check — CI only",
     "https://www.ghostscript.com/licensing.html"),
    ("`tesseract-ocr`", "distro", "Apache-2.0", "OCR oracle for scanned fixtures",
     "https://github.com/tesseract-ocr/tesseract/blob/main/LICENSE"),
    ("PDFium (`pdfium-binaries`)", "pinned at P2", "BSD-3-Clause",
     "pixel goldens (the only oracle that catches wrong-glyph bugs)",
     "https://pdfium.googlesource.com/pdfium/+/refs/heads/main/LICENSE"),
]


def metadata() -> dict:
    raw = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    return json.loads(raw)


def render(meta: dict) -> str:
    workspace_ids = set(meta["workspace_members"])
    rows = []
    for pkg in meta["packages"]:
        if pkg["id"] in workspace_ids:
            continue
        if pkg["source"] is None:
            continue
        licence = pkg.get("license") or "UNKNOWN — verify before shipping"
        rows.append((pkg["name"], pkg["version"], licence, pkg["source"]))
    rows.sort(key=lambda r: r[0].lower())

    lines = [
        "# DEPS.md — dependency ledger (generated)",
        "",
        "**Generated by `scripts/gen-deps.py` from `cargo metadata`. Do not hand-edit.**",
        "Run it after any dependency change and commit the result with the change",
        "(AGENTS.md rule 6).",
        "",
        "## Licence policy for shipped code",
        "",
        "Shipped default features must be **permissive-only** — even though pdfrtl itself is",
        "AGPL-3.0-or-later. Reason: we sell a commercial licence on top, and you cannot",
        "sublicense copyleft code you do not own. See",
        "`docs/decisions/0003-permissive-only-default-features.md`. Allowed: MIT, MIT-0,",
        "Apache-2.0, BSD-2/3-Clause, ISC, Unicode-3.0, Unicode-DFS-2016, Zlib, MPL-2.0",
        "(file-level), CC0-1.0, Unlicense, BSL-1.0, OpenSSL, FTL. Denied: GPL-2.0/3.0,",
        "AGPL-3.0, LGPL-2.1/3.0, SSPL, BUSL.",
        "",
        f"## Resolved dependencies ({len(rows)})",
        "",
        "| crate | version | licence | source |",
        "|---|---|---|---|",
    ]
    for name, version, licence, source in rows:
        short = source.split("+")[0].replace("registry+", "").replace("sparse+", "")
        lines.append(f"| `{name}` | {version} | {licence} | {short} |")

    lines += [
        "",
        "## Verification-only tools (never linked, never bundled)",
        "",
        "| tool | version | licence | role | evidence |",
        "|---|---|---|---|---|",
    ]
    for name, version, licence, role, url in ORACLES:
        lines.append(f"| {name} | {version} | {licence} | {role} | {url} |")
    lines += [
        "",
        "Only `pdftotext` and `tesseract` are permissive enough to be optional *shipped*",
        "features later; the AGPL/GPL ones stay in CI forever. Record that decision here if",
        "it ever changes.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    text = render(metadata())
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/DEPS.md is stale — run: python3 scripts/gen-deps.py", file=sys.stderr)
            return 1
        print("docs/DEPS.md is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
